window.JOKES = [
  { question: "O que é, o que é? Tem dentes, mas não morde?", answer: "O pente." },
  { question: "O que é, o que é? Quanto mais se tira, maior fica?", answer: "O buraco." },
  { question: "O que é, o que é? Tem cabeça e dentes, mas não é gente nem animal?", answer: "O alho." },
  { question: "O que é, o que é? Tem folhas, mas não é árvore?", answer: "O livro." },
  { question: "O que é, o que é? Tem pescoço, mas não tem cabeça?", answer: "A garrafa." },
  { question: "O que é, o que é? Quanto mais seca, mais molhada fica?", answer: "A toalha." },
  { question: "O que é, o que é? Tem olhos, mas não vê?", answer: "A batata." },
  { question: "O que é, o que é? Cai em pé e corre deitado?", answer: "A chuva." },
  { question: "O que é, o que é? Tem coroa, mas não é rei?", answer: "O abacaxi." },
  { question: "O que é, o que é? Tem mãos, mas não bate palmas?", answer: "O relógio." },
  { question: "O que é, o que é? Pode viajar pelo mundo inteiro sem sair do canto?", answer: "O selo." },
  { question: "O que é, o que é? Tem cidades, rios e florestas, mas não tem casas, água nem árvores?", answer: "O mapa." },
  { question: "O que é, o que é? Tem uma perna e um chapéu?", answer: "O cogumelo." },
  { question: "O que é, o que é? É cheio de furos, mas consegue segurar água?", answer: "A esponja." },
  { question: "O que é, o que é? Nasce grande e morre pequeno?", answer: "A vela." },
  { question: "O que é, o que é? Enche uma sala inteira, mas não ocupa espaço?", answer: "A luz." },
  { question: "O que é, o que é? Tem quatro pernas, mas não caminha?", answer: "A mesa." },
  { question: "O que é, o que é? Quebra sem nunca cair?", answer: "A promessa." },
  { question: "O que é, o que é? Você pode pegar, mas não pode jogar?", answer: "Um resfriado." },
  { question: "O que é, o que é? Tem um olho só e não enxerga?", answer: "A agulha." },
  { question: "O que é, o que é? Corre, mas não tem pernas?", answer: "O rio." },
  { question: "O que é, o que é? Está sempre na sua frente, mas você nunca consegue ver?", answer: "O futuro." },
  { question: "O que é, o que é? Tem folhas e mostra os dias do ano?", answer: "O calendário." },
  { question: "O que é, o que é? Tem muitas teclas, mas não abre nenhuma porta?", answer: "O teclado." },
  { question: "O que é, o que é? Entra pela janela e ilumina a casa?", answer: "A luz do sol." },
  { question: "O que é, o que é? Sobe e desce, mas fica no mesmo lugar?", answer: "O elevador." },
  { question: "O que é, o que é? Tem boca e leito, mas não fala nem dorme?", answer: "O rio." },
  { question: "O que é, o que é? Tem pás, gira sem parar e não é barco?", answer: "O ventilador." },
  { question: "O que é, o que é? Tem cara e coroa, mas não é pessoa nem rainha?", answer: "A moeda." },
  { question: "O que é, o que é? Tem rabo, voa alto e gosta de vento?", answer: "A pipa." },
  { question: "O que é, o que é? Segue você durante o dia, mas desaparece no escuro?", answer: "A sombra." },
  { question: "O que é, o que é? Parece algodão no céu e não é travesseiro?", answer: "A nuvem." },
  { question: "O que é, o que é? Tem muitas cores e aparece depois da chuva?", answer: "O arco-íris." },
  { question: "O que é, o que é? Nasce de manhã e se esconde à noite?", answer: "O sol." },
  { question: "O que é, o que é? Brilha no céu, mas não é o sol?", answer: "A lua." },
  { question: "O que é, o que é? Pisca no céu sem ter olhos?", answer: "A estrela." },
  { question: "O que é, o que é? Bate no rosto, mas ninguém consegue enxergar?", answer: "O vento." },
  { question: "O que é, o que é? Responde quando você fala, mas nunca começa a conversa?", answer: "O eco." },
  { question: "O que é, o que é? Desaparece quando alguém diz seu nome?", answer: "O silêncio." },
  { question: "O que é, o que é? É seu, mas os outros usam mais do que você?", answer: "O seu nome." },
  { question: "O que é, o que é? Aumenta a cada aniversário?", answer: "A idade." },
  { question: "O que é, o que é? Acontece enquanto você dorme e pode levar você a qualquer lugar?", answer: "O sonho." },
  { question: "O que é, o que é? Chega quando o corpo pede descanso?", answer: "O sono." },
  { question: "O que é, o que é? Vem depois da noite e antes da tarde?", answer: "A manhã." },
  { question: "O que é, o que é? Chega quando o sol vai embora?", answer: "A noite." },
  { question: "O que é, o que é? Foi feita para caminhar, mas não sai do lugar?", answer: "A estrada." },
  { question: "O que é, o que é? É o olho da casa, mas não enxerga sozinho?", answer: "A janela." },
  { question: "O que é, o que é? Abre e fecha, mas não tem boca?", answer: "A porta." },
  { question: "O que é, o que é? Tem voz, mas não tem boca, e costuma ficar pendurado?", answer: "O sino." },
  { question: "O que é, o que é? Toca quando alguém chega, mas não tem mãos?", answer: "A campainha." },
  { question: "O que é, o que é? Faz uma pessoa falar com outra que está longe?", answer: "O telefone." },
  { question: "O que é, o que é? Tira um retrato sem usar lápis?", answer: "A câmera." },
  { question: "O que é, o que é? Mostra seu rosto sem ter olhos?", answer: "O espelho." },
  { question: "O que é, o que é? Tem duas lentes e ajuda os olhos?", answer: "Os óculos." },
  { question: "O que é, o que é? Tem língua, mas não fala, e fica dentro do sapato?", answer: "O calçado." },
  { question: "O que é, o que é? Tem pé, mas não caminha, e costuma ficar aos pares?", answer: "A meia." },
  { question: "O que é, o que é? Senta na cabeça, mas não pensa?", answer: "O chapéu." },
  { question: "O que é, o que é? Protege da chuva quando é aberto sobre a cabeça?", answer: "O guarda-chuva." },
  { question: "O que é, o que é? Protege do sol e pode ser levado para a praia?", answer: "O guarda-sol." },
  { question: "O que é, o que é? Tem duas lâminas e gosta de cortar papel?", answer: "A tesoura." },
  { question: "O que é, o que é? Tem números e ajuda a desenhar linhas retas?", answer: "A régua." },
  { question: "O que é, o que é? Escreve pequeno e vai ficando menor?", answer: "O lápis." },
  { question: "O que é, o que é? Apaga o que o lápis escreveu?", answer: "A borracha." },
  { question: "O que é, o que é? Pinta sem usar as mãos diretamente?", answer: "O pincel." },
  { question: "O que é, o que é? Mede o tempo com areia, mas não vai à praia?", answer: "A ampulheta." },
  { question: "O que é, o que é? Diz se está quente ou frio?", answer: "O termômetro." },
  { question: "O que é, o que é? Mostra se algo está leve ou pesado?", answer: "A balança." },
  { question: "O que é, o que é? Atrai o ferro sem fazer força com os braços?", answer: "O ímã." },
  { question: "O que é, o que é? Tem segredo e só abre com a combinação certa?", answer: "O cadeado." },
  { question: "O que é, o que é? Entra na fechadura e faz a porta abrir?", answer: "A chave." },
  { question: "O que é, o que é? Guarda uma carta e tem uma língua que cola?", answer: "O envelope." },
  { question: "O que é, o que é? Viaja fechada e leva notícias para alguém?", answer: "A carta." },
  { question: "O que é, o que é? Explica palavras em ordem alfabética?", answer: "O dicionário." },
  { question: "O que é, o que é? Tem notícias, mas não conversa?", answer: "O jornal." },
  { question: "O que é, o que é? Tem imagem e som, mas não é uma pessoa?", answer: "A televisão." },
  { question: "O que é, o que é? Fala sem aparecer na sala?", answer: "O rádio." },
  { question: "O que é, o que é? Pode ter vírus, mas não espirra?", answer: "O computador." },
  { question: "O que é, o que é? Cabe no bolso e pode fazer chamadas?", answer: "O celular." },
  { question: "O que é, o que é? Controla a televisão sem precisar chegar perto?", answer: "O controle remoto." },
  { question: "O que é, o que é? Tem fases, desafios e costuma ser jogado com controles?", answer: "O videogame." },
  { question: "O que é, o que é? Tem pontos e pode cair na mesa durante uma brincadeira?", answer: "O dado." },
  { question: "O que é, o que é? Tem reis, damas e valetes, mas não mora em um castelo?", answer: "O baralho." },
  { question: "O que é, o que é? Tem peças que precisam se juntar para formar uma imagem?", answer: "O quebra-cabeça." },
  { question: "O que é, o que é? É redonda, quica e gosta de brincar?", answer: "A bola." },
  { question: "O que é, o que é? Tem duas rodas e anda com a força das pernas?", answer: "A bicicleta." },
  { question: "O que é, o que é? Tem rodas, mas não leva passageiros de verdade?", answer: "O carrinho de brinquedo." },
  { question: "O que é, o que é? Faz a criança subir e descer em um parque?", answer: "O escorregador." },
  { question: "O que é, o que é? Vai para frente e para trás preso por cordas?", answer: "O balanço." },
  { question: "O que é, o que é? Pode ser de pano e gosta de receber abraços?", answer: "A boneca." },
  { question: "O que é, o que é? Late, abana o rabo e gosta de brincar?", answer: "O cachorro." },
  { question: "O que é, o que é? Mia, tem bigodes e gosta de dormir?", answer: "O gato." },
  { question: "O que é, o que é? Nada sem usar uma bicicleta?", answer: "O peixe." },
  { question: "O que é, o que é? Anda devagar levando a casa nas costas?", answer: "A tartaruga." },
  { question: "O que é, o que é? Carrega a própria casa e deixa um caminho brilhante?", answer: "O caracol." },
  { question: "O que é, o que é? Tem orelhas compridas e gosta de cenoura?", answer: "O coelho." },
  { question: "O que é, o que é? Gosta de bananas e vive pulando?", answer: "O macaco." },
  { question: "O que é, o que é? Tem tromba comprida e gosta de água?", answer: "O elefante." },
  { question: "O que é, o que é? Tem pescoço comprido e alcança folhas altas?", answer: "A girafa." },
  { question: "O que é, o que é? Tem listras e parece estar sempre de pijama?", answer: "A zebra." },
  { question: "O que é, o que é? Usa roupa preta e branca e gosta de lugares gelados?", answer: "O pinguim." },
  { question: "O que é, o que é? Bota ovos e faz cocoricó?", answer: "A galinha." },
  { question: "O que é, o que é? Anda na água e faz quá-quá?", answer: "O pato." },
  { question: "O que é, o que é? Trabalha em grupo e gosta de flores?", answer: "A abelha." },
  { question: "O que é, o que é? Começa como lagarta e termina com asas coloridas?", answer: "A borboleta." },
  { question: "O que é, o que é? É pequenina, organizada e gosta de carregar folhas?", answer: "A formiga." },
  { question: "O que é, o que é? Faz teias, mas não é pescador?", answer: "A aranha." },
  { question: "O que é, o que é? Pula perto da lagoa e faz coaxar?", answer: "O sapo." },
  { question: "O que é, o que é? Dá leite e faz mu?", answer: "A vaca." },
  { question: "O que é, o que é? Gosta de lama e faz oinc?", answer: "O porco." },
  { question: "O que é, o que é? É chamado de rei dos animais, mas não usa coroa?", answer: "O leão." },
  { question: "O que é, o que é? É amarela, comprida e vem em um cacho?", answer: "A banana." },
  { question: "O que é, o que é? Pode ser vermelha, verde ou amarela e tem sementes no meio?", answer: "A maçã." },
  { question: "O que é, o que é? Tem casca alaranjada e gomos por dentro?", answer: "A laranja." },
  { question: "O que é, o que é? É grande, verde por fora e vermelha por dentro?", answer: "A melancia." },
  { question: "O que é, o que é? Estoura no calor e vira uma nuvem branca de comer?", answer: "A pipoca." },
  { question: "O que é, o que é? Pode ter cobertura e aparece em festas de aniversário?", answer: "O bolo." },
  { question: "O que é, o que é? Tem massa redonda, queijo e muitos sabores?", answer: "A pizza." },
  { question: "O que é, o que é? É gelado, doce e pode derreter no sol?", answer: "O sorvete." },
  { question: "O que é, o que é? Cresce no forno e costuma ser cortado em fatias?", answer: "O pão." },
  { question: "O que é, o que é? Tem casca dura e miolo branco?", answer: "O coco." },
  { question: "O que é, o que é? É pequena, roxa ou verde e cresce em cachos?", answer: "A uva." },
  { question: "O que é, o que é? Tem muitas sementes por fora?", answer: "O morango." }
];
